# Use root/example as user/password credentials
version: "3.1"

services:
  server:
    image: golang:1.16-alpine
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGO_DATABASE: groups
      MONGO_HOST: mongo
      MONGO_PASSWORD: Password123
      MONGO_PORT: 27017
      MONGO_USERNAME: groupsUser
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go run main.go server"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: groups
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret789
    volumes:
      - ./dev/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SuperSecret789

volumes:
  mongo-data:
    driver: local
