// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	app "github.com/mattreidarnold/gifter/app"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// MessageType provides a mock function with given fields:
func (_m *Message) MessageType() app.MessageType {
	ret := _m.Called()

	var r0 app.MessageType
	if rf, ok := ret.Get(0).(func() app.MessageType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(app.MessageType)
	}

	return r0
}

// Payload provides a mock function with given fields:
func (_m *Message) Payload() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// PayloadType provides a mock function with given fields:
func (_m *Message) PayloadType() reflect.Type {
	ret := _m.Called()

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}
