// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/mattreidarnold/gifter/app"

	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// MessageBus is an autogenerated mock type for the MessageBus type
type MessageBus struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *MessageBus) Handle(_a0 context.Context, _a1 app.Message) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, app.Message) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterCommandHandler provides a mock function with given fields: _a0, _a1
func (_m *MessageBus) RegisterCommandHandler(_a0 reflect.Type, _a1 app.HandlerFunc) {
	_m.Called(_a0, _a1)
}

// RegisterEventHandler provides a mock function with given fields: _a0, _a1
func (_m *MessageBus) RegisterEventHandler(_a0 reflect.Type, _a1 app.HandlerFunc) {
	_m.Called(_a0, _a1)
}
